### ISSUE TITLE
Lecture/Lab files download

### ISSUE THREAD

**Issue by ghost** [siwells/set08101#1]
It's the same thing if I have to download a file from this website as it is if I have to download it from Moodle. 

Upload it to Moodle -- at least there it'll usually open in a new tab directly. It's also better for the student since the module information goes in the same spot. 

Thanks

**Comment by siwells** [comment]
Except as the archive of materials grows, particularly in terms of code examples, the use of a Git repository becomes more advantageous. For example, you will be able to clone all the materials using a single command to make your own archive, or use a single command, to pull all the changes from the site. This will save you time over pointing & clicking in the long run.
