### ISSUE TITLE
Can't find template for report (.tex)

### ISSUE THREAD

**Issue by dustydins** [siwells/set08101#2]
### Can you add template for report to resources?

It may be in repo somewhere, or maybe you told us it was somewhere else and I missed it. Either way I can't find it, would maybe be easier to find if it was in resources folder?

Cheers
Arran

**Comment by FrostyLabs** [comment]
http://github.com/edinburgh-napier/aux_latex_cw_template

**Comment by dustydins** [comment]
nice one, cheers!

**Comment by siwells** [comment]
Another solution, especially if you haven't used LaTeX before:
Go to the [ShareLaTeX website](http://www.sharelatex.com) and create an account. You can then search for "napier" within the available templates. The Napier template will open in the browser based editor and generate a PDF for you that you can download and add to your submission repository. This way you don't have to install the LaTeX software on your machine.

**Comment by FrostyLabs** [comment]
Hyperlink broken but a quick Google for ShareLaTeX was easy enough. Sure you update comment though :p

**Comment by siwells** [comment]
url fixed
